### ISSUE TITLE
메인페이지, 데일리로그 레이아웃 및 UI관련 작업

### ISSUE THREAD

**Issue by Pablaw** [BulletBoxProject/BulletBox-project-FE-#108]
## Description

데일리로그 레이아웃 및 UI관련 작업입니다.

## Todo

- [x] 불렛 추가하기
- [x] 메인페이지 할 일 목록 스타일링 작업
- [x] 메인페이지 레이아웃 작업
- [x] 메인페이지 할 일 목록 조회 기능(불렛,카테고리, 시간 포함)

## Etc

기타사항
