### ISSUE TITLE
데일리로그, 메인페이지 미구현 기능들 추가 작업

### ISSUE THREAD

**Issue by Pablaw** [BulletBoxProject/BulletBox-project-FE-#113]
## Description

데일리로그, 메인페이지 미구현 기능들 추가 작업입니다.

## Todo

- [x] 날짜 변경 시 (다른 영역 클릭 시) 데일로그 카테고리 선택 드롭다운, 할 일 추가 메뉴 닫힘 기능
- [x] 날짜 형식 월, 일이 한 자리일 경우 0추가 YY/MM/DD(Day)
- [x] 데일리로그 할 일 카테고리 색상 표시
- [x] 데일리로그 캘린더 투데이 기능(오늘 날짜 기준 현재 월로 이동)
- [x] 메인페이지 캘린더 투데이 기능(오늘 날짜 기준  현재 월로 이동, 오늘 날짜 할 일 불러오기)

## Etc

기타사항
