### ISSUE TITLE
메인페이지, 데일리로그 피드백 오류 수정 작업

### ISSUE THREAD

**Issue by Pablaw** [BulletBoxProject/BulletBox-project-FE-#118]
## Description

메인페이지, 데일리로그 피드백 오류 수정 작업입니다.

## Todo

- [x] 데일리로그 - "+ 눌렀을 때 “자주 쓰는 할일” ⇒ “루틴 불러오기” 로 바꾸면 좋을 것 같습니다."
- [x] 데일리로그 - "+ 누르고 둘 중 하나 고를 때 마우스 포인터가 클릭 버튼처럼 안 바뀌어서 이게 클릭이 가능한 건지 아닌 지 모를 것 같습니다. 이 부분 수정 가능하면 수정하면 좋을 것 같습니다."
- [x] 데일리로그 - "할 일 추가 시 글자 수 32 제한인데 33까지 됩니다. 33/32로 뜹니다."
- [x] 데일리로그 - "할 일 작성 시 내용이 길어지면 오른쪽으로 쭉 길어지는데, 아래로 늘어나게 할 수는 없을까요?"
- [x] 데일리로그 - "할 일 작성, 수정 시 카테고리를 골랐을 때 현재 어떤 카테고리가 골라졌는 지 알 수가 없습니다. 현재 선택된 카테고리를 알 수 있어야 할 것 같습니다."
- [x] 데일리로그 - "할 일 내용이 길어지면 데일리 로그 css가 깨집니다."
- [x] 데일리로그 - "할 일에 시간 설정 안 해놨는데, 메인 페이지에서만 0:0으로 시간이 뜹니다."
- [x] 데일리로그 - "수정 페이지의 css가 전반적으로 이상합니다."
- [x] 데일리로그 -  데일리 로그에서 불렛 위치가 서로 다릅니다.
- [x] 데일리로그 -  데일리 로그 시간 설정된 할 일 시간 표시하기
- [x] 데일리로그 -  데일리 로그 생성 시 카테고리 선택 표시 유지하기
-
## Etc

기타사항
