### ISSUE TITLE
배포 후 오류점검 및 기능 개선

### ISSUE THREAD

**Issue by Pablaw** [BulletBoxProject/BulletBox-project-FE-#147]
## Description

배포 후 오류점검 및 기능 개선작업입니다.

## Todo

- [x] 캘린더 외부 클릭 시 닫힘 기능(데일리로그, 수정페이지)
- [x] 데일리로그 페이지 에러 예외 처리 기능 로직 구현
- [x] 데일리로그 에러 메세지 화면 표시 기능
- [x] 메인 페이지 에러 메시지 표시
## Etc

기타사항
