### ISSUE TITLE
일기장 페이지 성능개선

### ISSUE THREAD

**Issue by suno0140** [BulletBoxProject/BulletBox-project-FE-#151]
## Description

일기장 페이지 성능개선

## Todo

- [ ] img파일교체
- [ ] 백그라운드 및 포그라운드 색상변경
- [ ] 버튼 접근 가능한 이름 부여
- [ ] 글꼴 크기 변경
- [ ] 탭 타겟 크기 변경

## Etc

기타사항
