### ISSUE TITLE
할일 목록 드롭다운 만들기

### ISSUE THREAD

**Issue by Pablaw** [BulletBoxProject/BulletBox-project-FE-#6]
## Description

할일 목록 드롭다운 만들기

## Todo

- [ ] 할일 목록 불렛 드롭다운 만들기
- [ ] 할일 목록 카테고리 드롭다운 만들기
- [ ] 360 * 740 사이즈 맞게 레이아웃 조정해보기

## Etc

기타사항

**Comment by Pablaw** [comment]
오후 2시 반 작업 시작

**Comment by Pablaw** [comment]
실시간 CRUD Socket 통신으로 결정.
상태관리관련 로직 필요성 없어짐.
불렛, 카테고리 함수 컴포넌트 재사용 가능.
