### ISSUE TITLE
캘린더 css 바꾸기, 일기장 , 도움말 Layout

### ISSUE THREAD

**Issue by suno0140** [BulletBoxProject/BulletBox-project-FE-#68]
## Description

캘린더 css 바꾸기
일기장 Layout 그리기
도움말 css 바꾸기

## Todo

- [x] 디자인처럼 캘린더 CSS 수정하기
- [x] 일기장 Layout 그리기
- [x] 도움말 CSS 수정

## Etc

기타사항
