### ISSUE TITLE
Startpage,  Mypage CSS 변경

### ISSUE THREAD

**Issue by suno0140** [BulletBoxProject/BulletBox-project-FE-#73]
## Description

Startpage, Mypage CSS 수정

## Todo

- [x] Startpage CSS 수정
- [x] Mypage CSS 수정
- [x] 루틴으로 이름 수정
- [x] 카테고리 전체적인 CSS 수정
- [x] 카테고리 modal창 입력완료시 불 들어오기
- [x] 카테고리 modal창 흰색색상 선택시 효과 수정

## Etc

기타사항
