### ISSUE TITLE
검색페이지 수정,삭제 기능 구현

### ISSUE THREAD

**Issue by suno0140** [BulletBoxProject/BulletBox-project-FE-#91]
## Description

검색페이지 수정,삭제 기능 구현

## Todo

- [x] 검색페이지 수정 기능 구현
- [x] 검색페이지 삭제 기능 구현
- [x] 검색페이지 CSS 수정

## Etc

기타사항
