### ISSUE TITLE
catogory 색상 표시 , routine CSS 수정, signUp CSS수정

### ISSUE THREAD

**Issue by suno0140** [BulletBoxProject/BulletBox-project-FE-#97]
## Description

catogory 색상 표시 , routine CSS 수정

## Todo

- [x] catogory 색상 선택 표시
- [x] routine Add버튼 배경색 추가
- [x] routine 별표시 추가
- [x] signUp CSS수정

## Etc

기타사항
